name: API Automation Tests

on:
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run API automation tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          URL: ${{ secrets.URL }}
          PUBLIC_API_TOKEN: ${{ secrets.PUBLIC_API_TOKEN}}
          
        run: mvn clean test
